# -*- coding: utf-8 -*-
"""Building Lasso Regression Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WD6tiW3WM-tK12RUp0rAIflf2mjeKGOv
"""

#import numpy array
import numpy as pd

class Lasso_Regression():

  def __init__(self, learning_rate, no_of_iterations, lambda_parameter):

    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations
    self.lambda_parameter = lambda_parameter


  def fit(self, X, Y):

    #number of training examples and number of features
    self.m, self.n = X.shape
    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y

    #implementing gradient descent algorithm for optimization
    for i in range(self.no_of_iterations):
      self.update_weights()


  def update_weights(self):
    Y_prediction = self.predict(self.X)

    dw = np.zeros(self.n)

    for i in range(self.n):
      if self.w[i]>0:
        dw[i] = (-(2*(self.X[:,i].dot(self.Y - Y_prediction)) + self.lambda_parameter)/self.m)

      else:
        dw[i] = (-(2*(self.X[:,i].dot(self.Y - Y_prediction)) - self.lambda_parameter)/self.m)


    db = -2 * np.sum(self.Y - Y_prediction)/self.m

    self.w = self.w - self.learning_rate*dw
    self.b = self.b - self.learning_rate*db



  def predict(self, X):
    return X.dot(self.w) + self.b