# -*- coding: utf-8 -*-
"""Movies recommendation system using machine learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4paiGizj49lDtd7I96uBiy6TvBioVwL
"""

#Importing the libaraies
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

#importin the dataset
movies_data = pd.read_csv('/content/movies.csv')

movies_data.head()

movies_data.shape

movies_data.info()

movies_data.describe()

movies_data.isnull().sum()

#selecting the relevant features
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

#replaing the missing values with null values
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

#combing all the 5 selected features
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']
print(combined_features)

#converting  text data into numerical data
vectorizer = TfidfVectorizer()

features_vector = vectorizer.fit_transform(combined_features)
print(features_vector)

#cosine similarity scores
similarity = cosine_similarity(features_vector)
print(similarity)

print(similarity.shape)

#getting the movie name from the user
movie_name = input('Enter your favourite movie name: ')

#creating a list with all the movies list in the data frame
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

#Finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

close_match = find_close_match[0]
print(close_match)

#finding the index values in the movies list
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

similarity_scores = list(enumerate(similarity[index_of_the_movie]))
print(similarity_scores)

len(similarity_scores)

#sorting similarity scores based movies
sorted_similar_movies = sorted(similarity_scores,key = lambda x:x[1],reverse = True)
print(sorted_similar_movies)

#print the name of similar movies based on the index
print('Movies suggested for you: \n')
i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if(i<100):
    print(i,'.',title_from_index)
    i+=1

#Move Recommandation System
#getting the movie name from the user
movie_name = input('Enter your favourite movie name: ')

#creating a list with all the movies list in the data frame
list_of_all_titles = movies_data['title'].tolist()


#Finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)


close_match = find_close_match[0]


#finding the index values in the movies list
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]


similarity_scores = list(enumerate(similarity[index_of_the_movie]))


#sorting similarity scores based movies
sorted_similar_movies = sorted(similarity_scores,key = lambda x:x[1],reverse = True)

#print the name of similar movies based on the index
print('Movies suggested for you: \n')
i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if(i<100):
    print(i,'.',title_from_index)
    i+=1