# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mvTW69jNSlYFlyNjAQUtuSDIe1uKlV1-
"""

#importing dependence

import numpy as np

class Logistic_Regression():

  def __init__ (self, learning_rate, no_of_iterations):

    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations

  def fit(self, X, Y):

    self.m, self.n = X.shape

    #initiating the bias and weight values
    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y

    #implementing gradient descent
    for i in range(self.no_of_iterations):
      self.update_weights()


  def update_weights(self):

    #Y_hat formula (sigmoid function)

    Y_hat = 1 / (1 + np.exp(-(self.X.dot(self.w) + self.b)))

    #derivatives

    dw = (1 / self.m) * np.dot(self.X.T, (Y_hat - self.Y))
    db = (1 / self.m) * np.sum(Y_hat - self.Y)

    #updating the weights
    self.w = self.w - self.learning_rate * dw
    self.b = self.b - self.learning_rate * db



  def predict(self, X):

    Y_pred = 1 / (1 + np.exp(-(X.dot(self.w) + self.b)))
    Y_pred = np.where(Y_pred > 0.5, 1, 0)
    return Y_pred


import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#loading the dataset
diabetes_dataset = pd.read_csv('/content/diabetes (1).csv')

#print first 5 data
diabetes_dataset.head()

#number of rows and columns
diabetes_dataset.shape

#getting the  statistic measures of the data
diabetes_dataset.describe()

diabetes_dataset['Outcome'].value_counts()

# separating the dataset and levels
X = diabetes_dataset.drop(columns = 'Outcome', axis=1)
Y = diabetes_dataset['Outcome']

print(X)

print(Y)

scaler = StandardScaler()

scaler.fit(X)

standaraised_data = scaler.transform(X)
print(standaraised_data)

X = standaraised_data
Y = diabetes_dataset['Outcome']

print(X)
 print(Y)

#Train and split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

model = Logistic_Regression(learning_rate=0.01, no_of_iterations=1000)

model.fit(X_train, Y_train)

#Model Evaluation
#Accuracy  count
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score( Y_train, X_train_prediction)
print('Accuracy score of the training data : ', training_data_accuracy)

#Making a Predictive System
input_data = (5,166,72,19,175,25.8,0.587,51)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = model.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

