# -*- coding: utf-8 -*-
"""Implementing SVM Classifier From Scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UvKHVdmmwO3_LF_K7lZ_-LbILvjCD9v_
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import SVM

diabetes_dataset = pd.read_csv('/content/diabetes (1).csv')

diabetes_dataset.head()

diabetes_dataset.tail()

diabetes_dataset.shape

diabetes_dataset.info()

diabetes_dataset.describe()

diabetes_dataset['Outcome'].value_counts()

X = diabetes_dataset.drop(columns='Outcome', axis = 1 )
Y = diabetes_dataset['Outcome']

print(X)
print(Y)

#Data Standardization
scaler = StandardScaler()
scaler.fit(X)
standardized_data = scaler.transform(X)
print(standardized_data)

X = standardized_data
Y = diabetes_dataset['Outcome']


print(X)
print(Y)

#Train data and split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

#Train the model
#Support Vector Classifier
classifier = SVM.SVM_Classifier(learning_rate=0.001, no_of_iterations=1000, lambda_parameter=0.01)
classifier.fit(X_train, Y_train)

#Model Evaluation
#Accuracy Score
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print('Accuracy score on training data : ', training_data_accuracy)

X_test_prediction = classifier.predict(X_test)
testing_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print('Accuracy score on testinging data : ', testing_data_accuracy)

#Building the predictive system
# Add sample data to the input_data tuple
input_data = (1, 85, 66, 29, 0, 26.6, 0.351, 31)
#changing the input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')