# -*- coding: utf-8 -*-
"""Cusomer Segment using K-Means Clisting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJEZT8zw0DhghLTM5gEejXgxVqH9wV3G
"""

#Importing Libarais
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

#im[porting dataset
customer_segment = pd.read_csv('/content/Mall_Customers.csv')
customer_segment.head()

customer_segment.shape

customer_segment.info()

customer_segment.describe()

customer_segment.isnull().sum()

sns.set()

#Choosing the annual income Column & Spending score Column
X = customer_segment.iloc[:,[3,4]].values
print(X)

#finding wcss value for different numbef of custing
wcss = []
for i in range(1,11):
  kmeans = KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)

plt.plot(range(1,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('wcss')
plt.show()

#Tring the clusting model
kmeans = KMeans(n_clusters=5,init='k-means++',random_state=0)
y_kmeans = kmeans.fit_predict(X)
print(y_kmeans)

#showing the clusting model
plt.figure(figsize=(8,8))
plt.scatter(X[y_kmeans == 0,0],X[y_kmeans == 0,1],s=100,c='green',label='Cluster 1')

plt.scatter(X[y_kmeans == 1,0],X[y_kmeans == 1,1],s=100,c='red',label='Cluster 2')

plt.scatter(X[y_kmeans == 2,0],X[y_kmeans == 2,1],s=100,c='blue',label='Cluster 3')

plt.scatter(X[y_kmeans == 3,0],X[y_kmeans == 3,1],s=100,c='yellow',label='Cluster 4')

plt.scatter(X[y_kmeans == 4,0],X[y_kmeans == 4,1],s=100,c='orange',label='Cluster 5')


#plot the controls
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=300,c='cyan',label='Centroids')

plt.title('Customer Groups')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.show()