# -*- coding: utf-8 -*-
"""Lin reg implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMyqWluGIuHGy2OiJ2xEp9ub1cZPOZme
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import Lin_reg_model as LR

import pandas as pd
salary_data = pd.read_csv('/content/salary_data.csv')

#print dataframe
salary_data.head()

salary_data.tail()

salary_data.shape

X = salary_data.iloc[:,:-1].values
Y = salary_data.iloc[:,-1].values

print(X)
print(Y)

#Spliting the datset into training & test data
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

#Training the linear Regression
model = LR.Linear_Regression(learning_rate = 0.02,no_of_iterations=1000)

model.fit(X_train,Y_train)

print('Weight=',model.w[0])
print('Bias=',model.b)

#y = 9570(X) - 24384

#salary =  9570(experience) - 24384

test_data_prediction = model.predict(X_test)
print(test_data_prediction)

#vizualaizing the prediction values
plt.scatter(X_test,Y_test)
plt.plot(X_test,test_data_prediction,color='red')
plt.xlabel('Experience')
plt.ylabel('Salary')
plt.title('Salary Vs Experience')
plt.show()